dotenv: .env

networks:
  default: sepolia
  mainnet:
    host: ${WEB3_INFURA_URL}
    chain_id: 1
  goerli:
    host: ${WEB3_INFURA_URL_GOERLI}
    chain_id: 2
  mainnet_fork:
    host: https://127.0.0.1
    chain_id: 1
  sepolia:
    host: ${WEB3_INFURA_SEPOLIA_URL}
    chain_id: 11155111
compiler:
  vyper:
    version: 0.3.6

settings:
  gas_limit: "100000000000"
  gas_price: "5*10**10"